package com.cathy.example.mybatisspringbootdemo;

import lombok.Data;

@Data
public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PASSWORD
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.home_url
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private String homeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.screen_name
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private String screenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.activated
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private Integer activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.logged
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private Integer logged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.group_name
     *
     * @mbg.generated Fri Jun 29 17:23:09 CST 2018
     */
    private String groupName;


}